name: hds_desktop

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  shelf: ^1.3.2
  shelf_router: ^1.1.3
  shelf_web_socket: ^1.0.2
  web_socket_channel: ^2.2.0

  args: ^2.3.1
  ansicolor: ^2.0.1
  pubspec_parse: ^1.2.1
  pub_semver: ^2.1.1
  http: ^0.13.5

dev_dependencies:
  rexios_lints: ^3.0.0
