name: hds_desktop

environment:
  sdk: ^3.0.0

dependencies:
  shelf: ^1.3.2
  shelf_router: ^1.1.3
  shelf_web_socket: ^2.0.0
  web_socket_channel: ^3.0.1

  args: ^2.3.1
  ansicolor: ^2.0.1
  pub_semver: ^2.1.1
  http: ^1.1.0

dev_dependencies:
  rexios_lints: ^8.2.0
