name: Create Release

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  build:
    strategy:
      matrix:
        type:
          - { name: linux, os: ubuntu-latest }
          - { name: macos_intel, os: macos-latest }
          - { name: macos_apple_silicon, os: flyci-macos-large-latest-m1 }
          - { name: windows, os: windows-latest }
    runs-on: ${{ matrix.type.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1

      - name: Install dependencies
        run: dart pub get

      - name: Compile
        run: dart compile exe bin/hds_desktop.dart -o hds_desktop_${{ matrix.type.name }}

      - name: Archive artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.type.name }}
          path: hds_desktop_${{ matrix.type.name }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: success()

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Add execution permission
        run: chmod +x ./*

      - name: Create release draft
        uses: ncipollo/release-action@v1
        with:
          artifacts: "linux/*,macos_intel/*,macos_apple_silicon/*,windows/*"
          draft: true
